[package]
name = "proto"
version = "0.1.0"
authors = ["tom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "2.15", features = ["with-bytes"] }

[build-dependencies]
glob = "0.3"